name: Matrix Calculator CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ doxygen graphviz

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build project
      run: |
        cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}

    - name: Run tests
      run: |
        cd ${{github.workspace}}/build
        ctest --output-on-failure -C ${{matrix.build-type}}

    - name: Generate documentation
      run: |
        doxygen Doxyfile

    - name: Test documentation generation
      run: |
        if [ -f "docs/html/index.html" ]; then
          echo "✅ Documentation generated successfully"
          echo "Generated files:"
          ls -la docs/html/ | head -10
        else
          echo "❌ Documentation generation failed"
          exit 1
        fi

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation-${{matrix.build-type}}
        path: docs/html/
        retention-days: 7

  code-quality:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Basic code quality checks
      run: |
        echo "📁 Project structure:"
        find . -name "*.cpp" -o -name "*.h" | head -10
        echo ""
        echo "📏 Checking for large files:"
        find . -name "*.cpp" -o -name "*.h" | xargs wc -l | sort -nr | head -5
